RS-232/485 module & ModBus
savushkin-r-d/T1-PLCnext-Scales pull request #2
Opened 2022-05-04 11:47 UTC by YarickBSTU

2022-05-05 09:12 UTC, idzm requested changes

2022-05-05 09:12 UTC, idzm commented on DOC/README.md
> +## Настройки Bus Coupler для работы с последовательным интерфейсом RS-232
Неплохо бы добавить общее описание стенда (с фото) - из каких элементов состоит, для чего будет использоваться и т.п.

2022-05-05 14:17 UTC, AlexandrBehunkov commented
@YarickBSTU было бы неплохо ссылки в содержание добавить, для быстрого перехода к необходимому разделу.

2022-05-20 07:47 UTC, idzm approved these changes

2022-05-20 08:04 UTC, AlexandrBehunkov approved these changes

2022-05-20 08:37 UTC, VadimZezyotkoATP approved these changes

2022-05-20 08:51 UTC, merged